# Generated by Django 5.0 on 2025-11-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storeproductrelation',
            constraint=models.UniqueConstraint(fields=('product', 'store'), name='unique_product_per_store'),
        ),
    ]
