# Generated by Django 5.2.8 on 2026-03-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_managers_alter_product_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='store',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='storeproductrelation',
            managers=[
            ],
        ),
    ]
