# Generated by Django 5.2.8 on 2026-05-08 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('-created_at',), 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterModelOptions(
            name='storeproductrelation',
            options={'verbose_name': 'Store-Product', 'verbose_name_plural': 'Store-Products'},
        ),
        migrations.AddField(
            model_name='category',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Kazakh)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kz',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Name (Kazakh)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Kazakh)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_kz',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Name (Kazakh)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='store',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Kazakh)'),
        ),
        migrations.AddField(
            model_name='store',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Russian)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Related category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(verbose_name='Description (English)'),
        ),
    ]
