# Generated by Django 5.2.8 on 2026-05-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description_kz',
            new_name='description_kk',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_kz',
            new_name='name_kk',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_kz',
            new_name='description_kk',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_kz',
            new_name='name_kk',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='description_kz',
            new_name='description_kk',
        ),
    ]
