# Generated by Django 5.2.8 on 2026-05-08 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartitem_options_alter_order_options_and_more'),
        ('users', '0004_alter_customuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.address', verbose_name='Address'),
        ),
    ]
