# Generated by Django 5.2.8 on 2026-01-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'default_related_name': 'addresses', 'verbose_name_plural': 'Addresses'},
        ),
    ]
